# Automatically generated by configure - do not modify
TARGET_X86_64=y
TARGET_NAME=x86_64
TARGET_BASE_ARCH=i386
TARGET_ABI_DIR=x86_64
CONFIG_KVM=y
CONFIG_VHOST_NET=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/ub/DQEMU/gdb-xml/i386-64bit.xml /home/ub/DQEMU/gdb-xml/i386-64bit-core.xml /home/ub/DQEMU/gdb-xml/i386-64bit-sse.xml
CROSS_CC_GUEST="cc"
CROSS_CC_GUEST_STATIC=y
CONFIG_I386_DIS=y
CONFIG_I386_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
