obj-y = main.o syscall.o strace.o mmap.o signal.o \
	elfload.o linuxload.o uaccess.o uname.o \
	safe-syscall.o $(TARGET_ABI_DIR)/signal.o \
        $(TARGET_ABI_DIR)/cpu_loop.o exit.o \
	set.o offload_server.o offload_client.o offload_common.o

obj-$(TARGET_HAS_BFLT) += flatload.o
obj-$(TARGET_I386) += vm86.o
obj-$(TARGET_ARM) += arm/nwfpe/
obj-$(TARGET_M68K) += m68k-sim.o
